# Training
batch_size: 2 #batch_size per a GPU
data_root: './' #./ == vctk/raw/VCTK-Corpus
start_epoch: 0
num_epochs: 1000
checkpoint: 
save_path: './speech_output'
num_workers: 1
train_val_split: 0.8
lr: 0.0002

# Audio
sr: 16000 #Sampling rate
res_type: 'kaiser_fast' #Resampling algorithm
top_db: 20 #The threshold (in decibels) below reference to consider as silence
length: 7680

# Mu-law
quantize: 256

# Encoder
input_dim: 256

# VQ
d: 768
k: 64
beta: 0.25
decay: # 0.99

# WaveNet Decoder
n_loop: 2
n_layers: 20 # n_layers % n_loop == 0
filter_size: 3
residual_channels: 768
gate_channels: 768
skip_out_channels: 256
global_condition_dim: 128
local_condition_dim: 768

# Features Decoder
